# Generated by Django 2.2.7 on 2020-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=400)),
                ('puc_date', models.DateField()),
            ],
        ),
    ]
